import { Open_Sans } from "next/font/google";
import Providers from "./providers";
import { ReactNode } from "react";
import "./globals.css";

const openSans = Open_Sans({
   variable: "--font-open-sans",
   subsets: ["latin"],
   weight: ["300", "400", "600", "700"],
});

export const metadata = {
   title: "BrewHouse",
   description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
   return (
      <html lang="en">
         <body className={`${openSans.variable} antialiased`}>
            <Providers>{children}</Providers>
         </body>
      </html>
   );
}
